### ISSUE TITLE
Fatal error: Uncaught exception 'Requests_Exception' with message 'cURL error 28

### ISSUE THREAD

**Issue by NitinPrakash** [razorpay/razorpay-php-testapp#1]
When i press paynow button and validate a payment this error is appearing

Fatal error: Uncaught exception 'Requests_Exception' with message 'cURL error 28: Operation timed out after 10003 milliseconds with 0 out of -1 bytes received' in /opt/lampp/htdocs/rpay_app/libs/razorpay-php-master/vendor/rmccue/requests/library/Requests/Transport/cURL.php:280 Stack trace: #0 /opt/lampp/htdocs/rpay_app/libs/razorpay-php-master/vendor/rmccue/requests/library/Requests/Transport/cURL.php(123): Requests_Transport_cURL->process_response(false, Array) #1 /opt/lampp/htdocs/rpay_app/libs/razorpay-php-master/vendor/rmccue/requests/library/Requests.php(317): Requests_Transport_cURL->request('https://api.raz...', Array, Array, Array) #2 /opt/lampp/htdocs/rpay_app/libs/razorpay-php-master/src/Request.php(25): Requests::request('https://api.raz...', Array, Array, 'POST', Array) #3 /opt/lampp/htdocs/rpay_app/libs/razorpay-php-master/src/Entity.php(45): Razorpay\Api\Request->request('POST', 'payments/pay_30...', Array) #4 /opt/lampp/htdocs/rpay_app/libs/razorpay-php-master/src/Payment.php(37): Razorpay\Api\Entity->reque in /opt/lampp/htdocs/rpay_app/libs/razorpay-php-master/vendor/rmccue/requests/library/Requests/Transport/cURL.php on line 280

**Comment by shashankkumar** [comment]
Looks like normal request timeout error. We will handle it next update.
Although, did the timeout occurred due to our server or on your end due to bad connection?

**Comment by captn3m0** [comment]
Stale issue, closing

**Comment by badalsingh62** [comment]
Uncaught exception 'Requests_Exception' with message 'No working transports found' in razorpay-php/libs/Requests-1.8.0/library/Requests.php:215
--
&nbsp; | Stack trace:
