### ISSUE TITLE
Unable to echo payment amount on verify.php

### ISSUE THREAD

**Issue by mdanish2012** [razorpay/razorpay-php-testapp#10]
if ($success === true)
{
    $html = "<p>Your payment was successful</p>
             <p>Payment ID: {$_POST['razorpay_payment_id']}</p>";
              $txnid = $_POST['razorpay_payment_id'];
echo  $amount

**Comment by captn3m0** [comment]
This looks like a PHP issue, and not a Razorpay SDK issue. (Note that the amount is not passed in the post parameters after a successful payment).

Please use StackOverflow for such queries.

**Comment by mdanish2012** [comment]
There is no issue in php everything is working fine. Main concern is amount
should be echo on verify.php
