### ISSUE TITLE
Change Text of Button in pay.php

### ISSUE THREAD

**Issue by sau6402** [razorpay/razorpay-php-testapp#6]
This may look like a very basic question, but I am unable to change the text of button in pay.php
There is no code for that button in the page and it appears due to the script, I believe.

I was able to change the CSS via changing the .razorpay-payment-button class.
Please help me to change the button name from "Pay Now" to something else.

--
Regards
SAurabha J

**Comment by ankitstarski** [comment]
You can use the attribute `data-buttontext` in order to do it.

**Comment by captn3m0** [comment]
This is documented in the Automatic Checkout documentation: https://docs.razorpay.com/docs/checkout-form#automatic-checkout

**Comment by dbrax** [comment]
thank you it helped alot
