### ISSUE TITLE
Redirect to index.html on pressing close

### ISSUE THREAD

**Issue by sau6402** [razorpay/razorpay-php-testapp#7]
I am unable to figure out a way to redirect to index.html on clicking on the close button on the checkout popup.

Please guide.

--
Regards
SAurabha J

**Comment by mayankamencherla** [comment]
@sau6402 Hi,

Please head over to checkout / manual.php. On line 25, you'll see `ondismiss`, with the next line saying 
`console.log("This code runs when the popup is closed");`

Essentially, you can alter your code at this point to redirect to index.html.
One example of doing it would be to use window.location to manipulate the browser url. Here is a link of some usage examples below:
https://www.w3schools.com/js/js_window_location.asp

Please let us know if there's anything else we can help you with.

**Comment by captn3m0** [comment]
Stale issue, closing

**Comment by NIMESH07** [comment]
var options = {
    "key": "<YOUR_KEY_ID>", // Enter the Key ID generated from the Dashboard
    "amount": "29935",
    "name": "Acme Corp",
    "description": "A Wild Sheep Chase is the third novel by Japanese author Haruki Murakami",
    "image": "http://example.com/your_logo.jpg",
    "handler": function (response){
        alert(response.razorpay_payment_id);
    },
    /**
      * You can track the modal lifecycle by * adding the below code in your options
      */
    "modal": {
        "ondismiss": function(){
            console.log('Checkout form closed');
        }
    }
};
var rzp1 = new Razorpay(options);
