### ISSUE TITLE
api.razorpay.com: temporary failure in name resolution

### ISSUE THREAD

**Issue by anurag308** [razorpay/razorpay-php-testapp#9]
Hello All,
I am able to get payment id from razorpay front end, bu when I trying to capture the payment with java api I am getting this error:
api.razorpay.com: temporary failure in name resolution.
I am testing it from test mode and key. Do I need to test with Live credentials?
I googled but didn't find any help.
Please help.

Thanks in advance.

**Comment by captn3m0** [comment]
Were you facing this intermittently? DNS resolution does not depend on live/test creds. Please check your network configuration.

**Comment by captn3m0** [comment]
Closing this issue (on the sample app repo), as this will need further development as per https://github.com/razorpay/razorpay-php/issues/79
